### ISSUE TITLE
wrong winning conditions?

### ISSUE THREAD

**Issue by darkfriend77** [ajuna-network/ajuna-games#7] opened 2022-06-23 14:29 UTC
![image](https://user-images.githubusercontent.com/17710198/175323934-7271b909-cb7a-4a40-962b-14a2d14c88f8.png)

**Comment by cowboy-bebug** [comment] 2022-06-26 23:54
The `winner` and `next_player` fields are currently set to `PlayerIndex`: https://github.com/ajuna-network/ajuna-games/blob/1850d8d6c16a47e6e6c9cd47e01c4edd1918123f/dot4gravity/src/lib.rs#L225-L228
(This was a quick workaround to avoid propagating the generic type `Player` all the way down)

To display it correctly, `game_state.players` must be indexed using `winner` / `next_player` fields

**Comment by cowboy-bebug** [comment] 2022-06-27 01:06
This should be fixed in https://github.com/ajuna-network/ajuna-games/pull/11

**Comment by darkfriend77** [comment] 2022-07-09 19:18
I apologize that I have not explained what I was pointing out. The index was not a problem at all.

In the game design document, the winning pattern was three squares and not a row of 4, we will need to change at a later point.

![image](https://user-images.githubusercontent.com/17710198/178119783-b985afba-0007-482d-a5ca-5f913535fcf6.png)

**Comment by cowboy-bebug** [comment] 2022-07-11 00:36
Thanks for the clarification!

**Comment by cowboy-bebug** [comment] 2022-08-08 00:42
Closing as the issue is tracked by [PLAT-381](https://ajunanetwork.atlassian.net/browse/PLAT-381).

**Closed as completed by cowboy-bebug** 2022-08-08 00:42 UTC
